### ISSUE TITLE
Router and Regexen and Captures

### ISSUE THREAD

**Issue by dataf3l** [kardeiz/reset-router#1]
In the documentation, it was not clear whether or not the captures captured by the regex somehow available in the Request object later, is this so?

**Comment by kardeiz** [comment]
@dataf3l, yes, regex captures are available in the `Context`/Request object.

The base `regex::Captures` object can be returned with `Context::captures`, which returns a `Option<regex::Captures>`.

We also provide a `Context::extract_captures`, which extracts the captures into a tuple of any objects that impl `FromStr`. This is currently implemented for up to 3 captures (but I could add more). It can be used like:

    let (id, slug): (i32, String) = req.extract_captures().unwrap();

The method will fail if there aren't enough captures or if the `parse` fails.

There is some (minimal) documentation here: https://docs.rs/reset-router/0.3.0/reset_router/struct.Context.html.

Hope this helps!

**Comment by dataf3l** [comment]
Awesome!, if I write a example, I'll post it here for future reference.

**Comment by dataf3l** [comment]
Thanks, @kardeiz, you make the world a better place.
